// IDR------------------------------

#define IDR_MAINFRAME             2
#define IDR_DRAWCLTYPE            3
#define IDR_DRAWCLTYPEUSE         4
#define IDR_DRAWCLTYPEBENDEF      5
#define IDR_DRAWCLTYPEFAHRPLAN    6
#define IDR_TABTYPE               7 // Ordner
#define IDR_DRAWCLTYPEWINDOW      8 // CWND
#define IDR_DRAWCLTYPEKUNDEN      9
#define IDR_DRAWCLTYPE_CNTR_IP    11

// IDS------------------------------

#define IDS_CANNOT_OPEN_DRAWDOC   10

// IDC------------------------------

#define IDC_PENCIL                101
#define IDC_WEIGHT                102
#define IDC_NOFILL                103
#define IDC_TEXT                  104
#define IDC_HUNDERTPROZENT        105
#define IDC_PROZENT               106
//#define IDC_ANGLE                 107
#define IDC_WINKEL                108

#define IDC_TAB_MARGIN            109
#define IDC_TAB_HEIGHT            110
#define IDC_ENABLE                111

#define IDC_EDITSTRING            112
#define IDC_STRINGBESCHREIBUNG    113
// IDD------------------------------

#define IDD_TEST_BITMAP_BUTTON1   12


#define IDD_ABOUTBOX              100
#define IDD_PROP_RECT             101
#define IDD_PROP_TEXT             102
#define IDD_PROP_ZOOM             103
#define IDD_VIEW_BAR              104
#define IDD_ORDERS                105

#define IDD_TAB_LOOK              106
#define IDD_TAB_STYLE             107

#define IDD_CONNDLG               108
#define IDD_STRINGDIALOG          109


// Weiter mit ID Dialog

#define ID_GESAMTCOUNT            110
#define ID_GESTEXT                111
#define ID_PARTBOX                112
#define ID_PARTCOUNT              113


// IDP------------------------------

#define IDP_BUSY                  100
#define IDP_OLE_INIT_FAILED       101
#define IDP_FAILED_TO_CREATE      102

// ID-------------------------------



#define ID_CANCEL_EDIT            32768
#define ID_VIEW_GRID              32769
#define ID_DRAW_SELECT            32770
#define ID_DRAW_LINE              32771
#define ID_DRAW_RECT              32772
#define ID_DRAW_ROUNDRECT         32773
#define ID_DRAW_ELLIPSE           32774
#define ID_OBJECT_LINECOLOR       32775
#define ID_OBJECT_FILLCOLOR       32776
#define ID_OBJECT_MOVETOFRONT     32777
#define ID_OBJECT_MOVETOBACK      32778
#define ID_OBJECT_MOVEFORWARD     32779
#define ID_OBJECT_MOVEBACK        32780
#define ID_VIEW_PAPERCOLOR        32781
#define ID_DRAW_POLYGON           32782
#define ID_VIEW_SHOWOBJECTS       32784
#define ID_EDIT_PROPERTIES        32785
#define ID_DRAW_BAHNHOF           32786
#define ID_CONNECT_BAHNHOF        32787
#define ID_DRAW_TEXT              32788
#define ID_ADD_DATA_OBJ           32792
#define ID_DRAW_NEU_ELEMENT       32793
#define ID_DRAW_ADD_ELEMENT       32794
#define ID_DRAW_ATTRIBUTE         32795
#define ID_DRAW_TABELLE           32796
#define ID_SET_FONT               32797
#define ID_DRAW_CIRCLE            32798
#define ID_ADD_ELEMENT            32799
#define ID_GET_FAHRKARTE          32800
#define ID_CREATE_WINDOW          32802

#define ID_APPLY                  32803
#define ID_FRAME                  32804

#define ID_ZOOM                   32805
#define ID_HUNDERTPROZENT         32806
#define ID_CLIENTCBOX             32807
#define ID_SERVERCBOX             32808
#define ID_GRAPHICS               32809
#define ID_TIMELINE               32810
#define ID_HELP_ORDERS            32811

#define ID_VIEW_NETZ_EDIT         32817
#define ID_VIEW_NETZ_USE          32818

#define ID_DRAW_MAKE_FAHRPLAN     32819
#define ID_DRAW_DELETE_FAHRPLAN   32820
#define ID_VIEW_ZUGFAHRTEN        32821

#define ID_CHOOSE_FAHRKARTE       32822
#define ID_DELETE_FAHRKARTE       32823

#define ID_NEU_SEITE              32824
#define ID_DELETE_SEITE           32825

#define ID_SEITE_UP               32826
#define ID_SEITE_DN               32827
#define ID_SEITE_HOME             32828
#define ID_SEITE_END              32829

#define ID_EDIT_TABELLE           32830
#define ID_ADD_BENDEFOBJ          32831
#define ID_INDICATOR_STATUS       32832

#define ID_GROUP_UP               32833 // Gruppen, siehe Listbox in Toolbar
#define ID_GROUP_DN               32834
#define ID_GROUP_HOME             32835
#define ID_GROUP_END              32836

#define ID_ADD_FAHRT              32837 
#define ID_ADD_REVERS_FAHRPLAN    32838 

#define ID_SET_STANDART_FONT      32839

#define ID_NEU_KUNDE              32840
#define ID_DELETE_KUNDE           32841

#define ID_DRAW_ADD_WAGEN         32842
#define ID_DRAW_ADD_SITZGRUPPE    32843
#define ID_DRAW_ADD_SITZ          32844


// ---------------------------------

#define IDW_EDIT                  32812
#define IDW_USE                   32813
#define IDW_BENDEF                32814
#define IDW_WINDOW                32815
#define IDW_DIALOG_BAR            32816
#define IDW_FAHRPLAN              32817
#define IDW_BENDEFCOMBO           32818
#define IDW_KUNDEN                32819
#define IDW_KUNDENCOMBO           32820
#define IDW_TOOLCOMBO             32821
