// drawtool.cpp - implementation for drawing tools
//
// This is a part of the Microsoft Foundation Classes C++ library.
// Copyright (C) 1992-1993 Microsoft Corporation
// All rights reserved.
//
// This source code is only intended as a supplement to the
// Microsoft Foundation Classes Reference and Microsoft
// QuickHelp and/or WinHelp documentation provided with the library.
// See these sources for detailed information regarding the
// Microsoft Foundation Classes product.


#include "stdafx.h"
#include <afxdlgs.h>
#include <string.h>
#include "drawcli.h"
#include "drawdoc.h"
#include "drawobj.h"
#include "basevw.h"
//#include "drawvw.h"
#include "mconnect.h"
#include "node.h"
#include "dataelem.h"
#include "dr_wnd.h"
#include "tabobj.h"
#include "drawtool.h"

#ifdef _DEBUG
#undef THIS_FILE
static char BASED_CODE THIS_FILE[] = __FILE__;
#endif

